server:
  port: 9002
  servlet:
    context-path: /client2
logging:
  level:
      com.spring.boot.test : debug

management:
  endpoints:
    web:
      exposure:
        include: "*"
show:
  message: HelloYAML