server:
  port: 9002
  servlet:
    context-path: /client2
logging:
  level:
      com.spring.boot.test : debug

spring:
  application:
    name: spring-boot-client-9002
  cloud:
    config:
      uri: http://localhost:9955
management:
  endpoints:
    web:
      exposure:
        include: *