server:
  port: 9998
#spring:
#  application:
#    name: eureke-server
eureka:
  instance:
    instance-id: eureka-${server.port}-id
    hostname: eureka-${server.port}
  #    prefer-ip-address: true   #以IP地址注册到服务中心，相互注册使用IP地址
  #    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  #    ip-address: #强制指定IP地址，默认会获取本机的IP地址
  client:
    register-with-eureka: false         # 表示是否注册自身到eureka服务器
    fetch-registry: false         # 是否从eureka上获取注册信息
    serviceUrl:
      defaultZone: http://eureka-99:9999/eureka
  server:
    eviction-interval-timer-in-ms: 3000     # 续期时间，即扫描失效服务的间隔时间（单位毫秒，默认是60*1000）
    enableSelfPreservation: false    # 设为false，关闭自我保护
#    renewalPercentThreshold: 0.49

